"""
Handball Coach AI — offline tactical intelligence engine.
"""

import math
import time
from dataclasses import dataclass, field
from enum import Enum
from collections import deque
from typing import Callable, Optional

SYSTEM_PROMPT = (
    "You are an elite, brutally analytical Handball Head Coach with 20 years of "
    "IHF experience. You receive real-time JSON match events generated by a "
    "computer-vision system: goals, shots, fast breaks, rule violations, player "
    "speed/stamina metrics, and formation states.\n\n"
    "Your ONLY job is to output 1 or 2 sharp, immediately actionable tactical "
    "commands for the sideline staff."
)

COURT_W, COURT_H = 40.0, 20.0
GOAL_Y1, GOAL_Y2 = 8.5, 11.5
R6, R9 = 6.0, 9.0

class AlertLevel(str, Enum):
    INFO, WARNING, DANGER, GOAL = "info", "warning", "danger", "goal"

class AlertType(str, Enum):
    SIX_METRE_VIOLATION     = "6m_violation"
    PASSIVE_PLAY            = "passive_play"
    TOO_MANY_PLAYERS        = "too_many_players"
    FAST_SUBSTITUTION       = "fast_substitution"
    FAST_BREAK_CHANCE       = "fast_break_chance"
    NUMERICAL_SUPERIORITY   = "numerical_superiority"
    NUMERICAL_INFERIORITY   = "numerical_inferiority"
    GOAL_OPEN               = "goal_open"
    WING_OPEN               = "wing_open"
    PIVOT_UNMARKED          = "pivot_unmarked"
    HOLE_IN_DEFENCE         = "hole_in_defence"
    PLAYER_TIRED            = "player_tired"
    SUBSTITUTION_HINT       = "substitution_hint"
    ROLE_DISCIPLINE         = "role_discipline"

@dataclass
class CoachAlert:
    alert_type: AlertType
    level: AlertLevel
    team: str
    message: str
    timestamp: float = field(default_factory=time.perf_counter)
    player_id: str = ""
    data: dict = field(default_factory=dict)

    def to_dict(self) -> dict:
        return {"type": self.alert_type.value, "level": self.level.value, "team": self.team, "message": self.message, "ts": round(self.timestamp, 3), "player_id": self.player_id}

IHF_RULES = {
    "rule_4_2":  "Maximum 7 players on court per team",
    "rule_7_6":  "Passive play: no clear attempt to attack after 25s possession",
    "rule_8_7b": "Player in opponent's goal area → free throw",
}

class HandballCoach:
    def __init__(self, team_a_attacks_right: bool = True):
        self._a_right = team_a_attacks_right
        self._event_sink: Optional[Callable[[dict], None]] = None
        self._last_alert: dict[str, float] = {}
        self._alert_debounce_s = 4.0
        self.alerts: deque[CoachAlert] = deque(maxlen=50)
        self._track_pos: dict[int, tuple] = {}   
        self._seen_slots: dict[int, int] = {}   
        self._slot_teams: dict[int, str] = {}   

    def update(self, tracks: list, ball_track, frame_n: int, fps: float, possession: Optional[str], court_det, analytics, pid_map: dict[int, str]) -> list[CoachAlert]:
        now = time.perf_counter()
        new_alerts: list[CoachAlert] = []

        self._update_positions(tracks, ball_track, court_det, fps)

        new_alerts += self._check_too_many_players(tracks, now)
        new_alerts += self._check_6m_violation(tracks, now)
        new_alerts += self._check_fast_break(tracks, ball_track, possession, now)
        new_alerts += self._check_numerical(tracks, now)
        new_alerts += self._check_goal_opportunity(tracks, ball_track, possession, now)
        new_alerts += self._check_defence(tracks, ball_track, possession, now)
        new_alerts += self._check_wing_open(tracks, ball_track, possession, now)
        new_alerts += self._check_pivot_unmarked(tracks, ball_track, possession, now)
        
        # التنبيهات الذكية الخاصة بالمراكز التي تعلمها النظام
        if analytics:
            new_alerts += self._check_substitution_hints(tracks, pid_map, analytics, now)
            new_alerts += self._check_role_discipline(tracks, pid_map, analytics, now)
            
        new_alerts += self._check_actual_substitutions(tracks, frame_n, fps, now)
        self._detect_formation(tracks, possession)

        for a in new_alerts:
            self.alerts.append(a)
            if self._event_sink is not None:
                try: self._event_sink(a.to_dict())
                except Exception: pass

        return new_alerts

    def set_event_sink(self, callback: Callable[[dict], None]) -> None:
        self._event_sink = callback

    def flip_sides(self) -> None:
        self._a_right = not self._a_right
        self._track_pos.clear()

    def recent_alerts(self, n: int = 8) -> list[dict]:
        return [a.to_dict() for a in list(self.alerts)[-n:]]

    def _update_positions(self, tracks, ball_track, court_det, fps) -> None:
        for t in tracks:
            if t.is_ball: continue
            xm, ym = t.cx / 1280 * 40.0, t.cy / 720 * 20.0   
            if court_det and court_det.is_calibrated:
                res = court_det.pixel_to_meter(t.cx, t.cy)
                if res: xm, ym = res
            self._track_pos[t.track_id] = (xm, ym)

    def _attack_dir(self, team: str) -> int:
        if team == "team_a": return 1 if self._a_right else -1
        return -1 if self._a_right else 1

    def _attack_goal_x(self, team: str) -> float:
        return COURT_W if self._attack_dir(team) > 0 else 0.0

    def _own_goal_x(self, team: str) -> float:
        return 0.0 if self._attack_dir(team) > 0 else COURT_W

    def _in_6m(self, xm: float, ym: float, goal_x: float) -> bool:
        if not (GOAL_Y1 - R6 <= ym <= GOAL_Y2 + R6): return False
        cx, cy1, cy2 = goal_x, GOAL_Y1, GOAL_Y2
        if ym < cy1: return math.hypot(xm - cx, ym - cy1) <= R6
        elif ym > cy2: return math.hypot(xm - cx, ym - cy2) <= R6
        else: return abs(xm - cx) <= R6

    # ── قراءة التمركز والالتزام بالخطة ──
    def _check_role_discipline(self, tracks, pid_map: dict, analytics, now: float) -> list[CoachAlert]:
        alerts = []
        for t in tracks:
            if getattr(t, 'is_ball', False): continue
            pid = pid_map.get(t.track_id)
            if not pid: continue
            prof = analytics.get_profile(pid)
            if not prof or not prof.inferred_role: continue
            
            role = prof.inferred_role
            xm, ym = self._track_pos.get(t.track_id, (None, None))
            if xm is None or ym is None: continue
            
            # جناح أيمن دخل لعمق الملعب وترك الطرف مكشوف
            if role == "RW" and ym > 9.0:
                if self._debounce(f"rw_drift_{pid}", now, 15.0):
                    alerts.append(CoachAlert(AlertType.ROLE_DISCIPLINE, AlertLevel.WARNING, t.team, f"Right Wing (S{t.track_id}) is drifting too far center (Y={ym:.1f}m). Wing is exposed!", player_id=pid))
            # جناح أيسر دخل لعمق الملعب
            elif role == "LW" and ym < 11.0:
                if self._debounce(f"lw_drift_{pid}", now, 15.0):
                    alerts.append(CoachAlert(AlertType.ROLE_DISCIPLINE, AlertLevel.WARNING, t.team, f"Left Wing (S{t.track_id}) is drifting too far center (Y={ym:.1f}m). Wing is exposed!", player_id=pid))
        return alerts

    def _check_too_many_players(self, tracks, now: float) -> list[CoachAlert]:
        alerts = []
        for team in ("team_a", "team_b"):
            players = [t for t in tracks if not t.is_ball and t.team == team]
            if len(players) > 7 and self._debounce(f"too_many_{team}", now):
                alerts.append(CoachAlert(AlertType.TOO_MANY_PLAYERS, AlertLevel.WARNING, team, f"{team.replace('team_','Team ')} has {len(players)} players! Rule 4:2 — max 7"))
        return alerts

    def _check_6m_violation(self, tracks, now: float) -> list[CoachAlert]:
        alerts = []
        for t in tracks:
            if t.is_ball or t.team not in ("team_a", "team_b"): continue
            xm, ym = self._track_pos.get(t.track_id, (None, None))
            if xm is None: continue
            if self._in_6m(xm, ym, self._attack_goal_x(t.team)) and self._debounce(f"6m_{t.track_id}", now, 2.0):
                alerts.append(CoachAlert(AlertType.SIX_METRE_VIOLATION, AlertLevel.WARNING, t.team, f"Attacker #{t.track_id} inside 6m zone — Rule 8:7b free throw", player_id=str(t.track_id)))
        return alerts

    def _check_fast_break(self, tracks, ball_track, possession, now) -> list[CoachAlert]:
        if ball_track is None or possession is None: return []
        att_team, def_team = possession, "team_b" if possession == "team_a" else "team_a"
        att_goal_x, dir_x = self._attack_goal_x(att_team), self._attack_dir(att_team)
        bx = self._track_pos.get(ball_track.track_id, (ball_track.cx / 1280 * 40, None))[0]

        def_between = sum(1 for t in tracks if not t.is_ball and t.team == def_team and self._track_pos.get(t.track_id, (None, None))[0] is not None and ((dir_x > 0 and bx < self._track_pos[t.track_id][0] < att_goal_x) or (dir_x < 0 and att_goal_x < self._track_pos[t.track_id][0] < bx)))
        att_ahead = sum(1 for t in tracks if not t.is_ball and t.team == att_team and self._track_pos.get(t.track_id, (None, None))[0] is not None and ((dir_x > 0 and self._track_pos[t.track_id][0] > bx - 3) or (dir_x < 0 and self._track_pos[t.track_id][0] < bx + 3)))

        if att_ahead > def_between + 1 and self._debounce(f"fastbreak_{att_team}", now, 3.0):
            return [CoachAlert(AlertType.FAST_BREAK_CHANCE, AlertLevel.DANGER, att_team, f"FAST BREAK — {att_ahead}v{def_between} advantage! Attack NOW", data={"attackers": att_ahead, "defenders": def_between})]
        return []

    def _check_numerical(self, tracks, now) -> list[CoachAlert]:
        alerts = []
        for att_team, def_team in [("team_a", "team_b"), ("team_b", "team_a")]:
            dir_x = self._attack_dir(att_team)
            att_zone = [t for t in tracks if not t.is_ball and t.team == att_team and self._in_attacking_half(t, dir_x)]
            def_zone = [t for t in tracks if not t.is_ball and t.team == def_team and self._in_attacking_half(t, dir_x)]
            diff = len(att_zone) - len(def_zone)
            if diff >= 2 and self._debounce(f"superiority_{att_team}", now): alerts.append(CoachAlert(AlertType.NUMERICAL_SUPERIORITY, AlertLevel.DANGER, att_team, f"Numerical superiority: {len(att_zone)}v{len(def_zone)} in attack zone"))
            elif diff <= -2 and self._debounce(f"inferiority_{att_team}", now): alerts.append(CoachAlert(AlertType.NUMERICAL_INFERIORITY, AlertLevel.WARNING, att_team, f"Outnumbered {len(att_zone)}v{len(def_zone)} — fall back"))
        return alerts

    def _check_goal_opportunity(self, tracks, ball_track, possession, now) -> list[CoachAlert]:
        if ball_track is None or possession is None: return []
        bx = self._track_pos.get(ball_track.track_id, (ball_track.cx / 1280 * 40, None))[0]
        att_goal_x, dir_x = self._attack_goal_x(possession), self._attack_dir(possession)
        dist_to_goal = abs(bx - att_goal_x)

        if dist_to_goal < 9.0:
            def_team = "team_b" if possession == "team_a" else "team_a"
            blockers = sum(1 for t in tracks if not t.is_ball and t.team == def_team and self._track_pos.get(t.track_id, (None, None))[0] is not None and abs(self._track_pos[t.track_id][1] - 10.0) < 4.0 and ((dir_x > 0 and bx < self._track_pos[t.track_id][0] < att_goal_x) or (dir_x < 0 and att_goal_x < self._track_pos[t.track_id][0] < bx)))
            if blockers == 0 and self._debounce(f"goal_open_{possession}", now, 2.0):
                return [CoachAlert(AlertType.GOAL_OPEN, AlertLevel.GOAL, possession, f"SHOOTING LANE OPEN — {dist_to_goal:.1f}m from goal! Shoot!")]
        return []

    def _check_defence(self, tracks, ball_track, possession, now) -> list[CoachAlert]:
        if ball_track is None or possession is None: return []
        alerts, def_team = [], "team_b" if possession == "team_a" else "team_a"
        def_players = [t for t in tracks if not t.is_ball and t.team == def_team]
        if len(def_players) < 3: return alerts

        positions = sorted([self._track_pos.get(t.track_id, (None, None))[1] for t in def_players if self._track_pos.get(t.track_id, (None, None))[1] is not None])
        for i in range(len(positions) - 1):
            gap = positions[i + 1] - positions[i]
            if gap > 4.5:
                gap_y = (positions[i] + positions[i + 1]) / 2
                if self._debounce(f"def_hole_{def_team}_{int(gap_y)}", now, 5.0):
                    alerts.append(CoachAlert(AlertType.HOLE_IN_DEFENCE, AlertLevel.WARNING, def_team, f"Defence gap {gap:.1f}m at y≈{gap_y:.1f}m — close the hole", data={"gap_m": round(gap, 1), "gap_y": round(gap_y, 1)}))
        return alerts

    def _check_wing_open(self, tracks, ball_track, possession, now) -> list[CoachAlert]:
        if ball_track is None or possession is None: return []
        def_team = "team_b" if possession == "team_a" else "team_a"
        for wing_y, label in [(2.0, "right wing"), (18.0, "left wing")]:
            defended = any(abs(self._track_pos.get(t.track_id, (None, None))[1] or 99 - wing_y) < 3.0 for t in tracks if not t.is_ball and t.team == def_team)
            if not defended and any(abs(self._track_pos.get(t.track_id, (None, None))[1] or 99 - wing_y) < 4.0 for t in tracks if not t.is_ball and t.team == possession):
                if self._debounce(f"wing_{label}", now, 4.0):
                    return [CoachAlert(AlertType.WING_OPEN, AlertLevel.DANGER, possession, f"{label.title()} is unguarded — play the ball wide!")]
        return []

    def _check_pivot_unmarked(self, tracks, ball_track, possession, now) -> list[CoachAlert]:
        if ball_track is None or possession is None: return []
        def_team, att_goal_x = "team_b" if possession == "team_a" else "team_a", self._attack_goal_x(possession)
        pivots = [t for t in tracks if not t.is_ball and t.team == possession and self._in_6m(self._track_pos.get(t.track_id, (None, None))[0] or -99, self._track_pos.get(t.track_id, (None, None))[1] or -99, att_goal_x)]
        
        for pivot in pivots:
            px_m, py_m = self._track_pos.get(pivot.track_id, (None, None))
            if px_m is None: continue
            guarded = any(math.hypot((self._track_pos.get(t.track_id, (None, None))[0] or 0) - px_m, (self._track_pos.get(t.track_id, (None, None))[1] or 0) - py_m) < 1.5 for t in tracks if not t.is_ball and t.team == def_team)
            if not guarded and self._debounce(f"pivot_unmarked_{possession}", now, 3.0):
                return [CoachAlert(AlertType.PIVOT_UNMARKED, AlertLevel.GOAL, possession, "PIVOT is unmarked at 6m — feed the pivot immediately!")]
        return []

    def _check_substitution_hints(self, tracks, pid_map: dict, analytics, now) -> list[CoachAlert]:
        alerts = []
        for t in tracks:
            if t.is_ball: continue
            pid = pid_map.get(t.track_id)
            if not pid: continue
            prof = analytics.get_profile(pid)
            if not prof: continue
            score = (3 if (getattr(prof, "total_sprint_count", 0) or 0) > 120 else 1 if (getattr(prof, "total_sprint_count", 0) or 0) > 80 else 0) + (3 if getattr(prof, "avg_speed_ms", 10) < 1.2 else 1 if getattr(prof, "avg_speed_ms", 10) < 1.5 else 0) + (2 if (getattr(prof, "total_distance_m", 0) or 0) > 4500 else 0) + (2 if getattr(prof, "stamina", 1) < 0.30 else 0)
            if score >= 2 and self._debounce(f"fatigue_{pid}", now, 20.0 if score >= 4 else 30.0):
                alerts.append(CoachAlert(AlertType.SUBSTITUTION_HINT if score >= 4 else AlertType.PLAYER_TIRED, AlertLevel.DANGER if score >= 4 else AlertLevel.INFO, t.team, f"#{t.track_id} {(getattr(prof, 'name', None) or f'slot {t.track_id}')} fatigue score {score} — {'SUBSTITUTE NOW' if score >= 4 else 'monitor closely'}", player_id=pid))
        return alerts

    def _check_actual_substitutions(self, tracks, frame_n: int, fps: float, now: float) -> list[CoachAlert]:
        occlusion_frames, purge_frames, active_ids = max(1, int(fps * 5.0)), max(1, int(fps * 30.0)), set()
        for t in tracks:
            if not t.is_ball: active_ids.add(t.track_id); self._seen_slots[t.track_id] = frame_n; self._slot_teams[t.track_id] = t.team
        alerts, to_purge = [], []
        for slot_id, last_seen in self._seen_slots.items():
            if slot_id in active_ids: continue
            absent = frame_n - last_seen
            if absent > purge_frames: to_purge.append(slot_id); continue
            if absent == occlusion_frames and self._debounce(f"sub_{slot_id}", now, 15.0):
                alerts.append(CoachAlert(AlertType.FAST_SUBSTITUTION, AlertLevel.WARNING, self._slot_teams.get(slot_id, "unknown"), f"Slot #{slot_id} left the court (absent {absent/fps:.0f}s) — possible substitution", data={"slot_id": slot_id, "absent_frames": absent}))
        for sid in to_purge: self._seen_slots.pop(sid, None); self._slot_teams.pop(sid, None)
        return alerts

    def _detect_formation(self, tracks, possession) -> dict:
        result = {}
        for team in ("team_a", "team_b"):
            players = [t for t in tracks if not t.is_ball and t.team == team]
            if len(players) < 4: continue
            in_own = sum(1 for t in players if abs((self._track_pos.get(t.track_id, (None, None))[0] or 20) - self._own_goal_x(team)) < 15)
            if team == possession: result[team] = {"mode": "attack", "formation": "3-2-1" if len(players) - in_own >= 5 else "balanced"}
            else: result[team] = {"mode": "defence", "formation": "6-0" if in_own >= 5 else "5-1" if in_own == 4 else "4-2"}
        return result

    @staticmethod
    def get_rule(rule_id: str) -> str: return IHF_RULES.get(rule_id, f"Rule {rule_id} not found")
    @staticmethod
    def all_rules() -> dict: return IHF_RULES.copy()

    def _debounce(self, key: str, now: float, debounce_s: float | None = None) -> bool:
        if now - self._last_alert.get(key, 0) >= (debounce_s or self._alert_debounce_s):
            self._last_alert[key] = now
            return True
        return False

    def _in_attacking_half(self, track, dir_x: int) -> bool:
        xm = self._track_pos.get(track.track_id, (None, None))[0]
        return False if xm is None else (xm > 20 if dir_x > 0 else xm < 20)